import * as OfflinePluginRuntime from 'offline-plugin/runtime';
OfflinePluginRuntime.install();

import 'normalize.css/normalize.css'
import 'blocklyMods/blockly'
import 'blocklyMods/toolbox'
import 'blocks/appendDefaultBlock'
import 'blocks/mutators'
import 'blocks/mixins'
import 'blocks/extensions'
import 'blocks/definitions'
import 'core/editorInit'
import 'generator/init'
import 'generator/blocks'
import 'core/splitView'
import 'core/toolboxSearch'
import 'core/open'
import 'core/updatePreview'
import 'core/save'
import 'core/export'